### ISSUE TITLE
Conflict with @solflare-wallet/utl-sdk

### ISSUE THREAD

**Issue by KoenRijpstra** [Bonfida/sns-sdk#74]
Using a clean next project and installing both @solflare-wallet/utl-sdk and @bonfida/spl-name-service results in the following error when using @solflare-wallet/utl-sdk:

```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at extendBorsh (webpack-internal:///(rsc)/./node_modules/@metaplex-foundation/mpl-core/dist/src/utils/borsh.js:14:26)
    at eval (webpack-internal:///(rsc)/./node_modules/@metaplex-foundation/mpl-core/dist/src/utils/borsh.js:30:25)
```

After investigating, I found that the issue started with @bonfida/spl-name-service version 2.3.3. It's unclear whether the problem lies with @solflare-wallet/utl-sdk or @bonfida/spl-name-service.

## Steps to Reproduce:

1. Create a new Next.js app with default settings:
    ```
    bunx create-next-app
    ```

2. Install the required packages:
    ```
    bun install @solflare-wallet/utl-sdk @bonfida/spl-name-service
    ```

3. Replace the content of `page.tsx` with the following code:
    ```javascript
    import { Client, Token } from "@solflare-wallet/utl-sdk";
    import { PublicKey } from "@solana/web3.js";
    
    export default async function Home() {
      const utl = new Client();
      const token: Token = await utl.fetchMint(
        new PublicKey("So11111111111111111111111111111111111111112")
      );
    
      return <>{token.logoURI}</>;
    }
    ```

4. Start the development server:
    ```
    bun run dev
    ```

**Comment by dr497** [comment]
Hi @KoenRijpstra! Thanks for opening the issue, I will investigate and get back to you

**Comment by dr497** [comment]
It looks like the issue you're encountering is related to how bun handles package resolutions, specifically with different versions of borsh.
Here are a few points to consider:
1. Bun vs. npm: The issue seems to be specific to bun. When using npm, everything works fine. You can see more details here: <URL>.
2. Version Change: In version 2.3.3 of @bonfida/spl-name-service, we upgraded to borsh 1.0.0. This change might be causing conflicts with other packages that rely on older versions of borsh.
3. No Direct Dependency: Our SDK does not have a dependency on @metaplex-foundation. The error you're seeing (TypeError: Cannot read properties of undefined (reading 'prototype')) seems to be related to how bun resolves borsh dependencies.
4. Dependency Conflicts: It appears that other packages in your project are relying on borsh versions earlier than 1.0.0. This version mismatch could be causing the issue.
To resolve this, you might want to try using npm instead of bun, or ensure that all packages in your project are compatible with borsh 1.0.0.
Hope this helps! If you have any more questions, feel free to ask.
Best regards,

**Comment by dr497** [comment]
It looks like the issue you're encountering is related to how bun handles package resolutions, specifically with different versions of `borsh`. When using npm, everything works fine. You can see more details here on this test repo https://github.com/dr497/test-issue/tree/main

Our SDK does not have a dependency on @metaplex-foundation. The error you're seeing `(TypeError: Cannot read properties of undefined (reading 'prototype'))` seems to be related to how bun resolves borsh dependencies. In version `2.3.3` of `@bonfida/spl-name-service`, we upgraded to borsh `1.0.0`. This change might be causing conflicts with other packages that rely on older versions of borsh.

To resolve this, you might want to try using npm instead of bun, or ensure that all packages in your project are compatible with `borsh >= 1.0.0`.

**Comment by KoenRijpstra** [comment]
Thanks, that explains a lot! Will lock it to 2.3.2 for now and maybe I can use `overrides` to fix the issue.
